export const PUBLICATION_LIST_REQUEST = 'PUBLICATION_LIST_REQUEST';
export const PUBLICATION_LIST_SUCCESS = 'PUBLICATION_LIST_SUCCESS';
export const PUBLICATION_LIST_FAIL = 'PUBLICATION_LIST_FAIL';

export const PUBLICATION_DETAILS_REQUEST = 'PUBLICATION_DETAILS_REQUEST';
export const PUBLICATION_DETAILS_SUCCESS = 'PUBLICATION_DETAILS_SUCCESS';
export const PUBLICATION_DETAILS_FAIL = 'PUBLICATION_DETAILS_FAIL';
